git:
  depth: 3
env:
  global:
  - secure: "OKc6Mojr/tBf2AP0IwZBeey0NXfrdxesfPhXlHPVQfbT4RbZwfaLnLbKsPV2MCRo0j5+vCxTiEEg+2tKIfpwOASyD8P0Qh3Isa4DjtueB8M/tdCzWYLGxJ6poGjMjd8cLUoExBfiNO7CL32B4Z83IEbpzC2ScPJRBnI2pmvCmniB9Wqt3yQUnlVc96e009ubrs6G5uMfzelAkVBsm9BexFxCtPBM5G6T8RDTKQ6h27pQlBjQnNn6s8JAod6u5byN4tmApW7ockham3sQ1c1+vTqnt97a6MS2O+G4/FdkJ/ex3I99wl1xHH6C89IicgN/xX+P/9JL4AWYP778AtRIXeSk3G6wMaWzeNYD+36T5iTvqniY0rqgPOcpnf78TjueUn57crqdt5tWaFUME7AB8/mSqPgKiiC1wuAoz85h/AOeiRtxd7zAHLk+blvIWOR+Z5yuHwCRFA7eemXriTfUU2LczS229IgD4yyqMYMVOksmo5bPmPL/vPsl0aIXQLEBS91OFxQKMPQu9gSJ3dqiObmhVnJ7OOhBxJ8deAC81nn76v6UaE7O0g4RiDeytOhiap/4MUjLDi9aR9WOX3rTvI5ZFxtKMMvFFjgs/0reWfdqW8kzCfPLzzaV83oYjsc5hhrQBBFN5gEbRwoIXdHvHMhqBU76jmQJF+J/KMcxGk4="
  - secure: "JDqvzWz0yehxBWzggNcRg2TUUolL0lX2y/ErBexkLmvNnUha8tU7IdN+2wcmiv2Jmhjnkv4hpvIMFqkiu2Nl2Lib+77lu22jLBkmwcfQzEdujmam7jkWr7Y/RxmF9FhkNViJ80/rtgCyGEHGBmMohJ90++Ix3FgMTIH6UbHbb6wGDAkN6C3KnBBPvjK/rIj3MuVFc0q7vVHTIRCAFZ/b6zDGozlDorbqt0yKEhQBW/U/f4jkeuYzjsHdKNtWzdf1VFaZz2YxynM6OE9k4rbWpPPeAM2gOp2+mAEbEZzavgXkNpEu3rvdGBjeQEyEpV57R2KE4xodp3xmXoIF4s05xAo4sn3VzGdtBG8mRxfaUczKr43Ys3wIv13zXYCsmb1NF9xG8SGueRdEK+r2BY6wtLj6K/lG3NEx25UPfp16OQoEzHI8F7yNmVGyb3oKphrq+7OJgUOyeL8OQAiQiK0lTuEr6T+0r36AmhdKKOsQxO8vGLhIAUjRSC6tcMERK4rHQFbgiPEFeA9yBJ9MSbVGOzgietlxS1hV1CidTcrdb+LweSDRY/sNpe/B2HGRKhycXRcAwhf4R1kQ4/G9KqitF13BNzNX6rnkUt0fHaH3kddSR1CkgFFF9sZ12bnRJQK8Til1KwLmzaL0pcsAGe+DAYUxulQKDwOUVbZU2nLmoiA="

language: objective-c
compiler: clang
osx_image: xcode9.4

before_script:
- git clone --depth 1 https://github.com/LWJGL-CI/bx.git ../bx
- git clone --depth 1 https://github.com/LWJGL-CI/bimg.git ../bimg

before_install:
- brew update

install:
- brew unlink python
- brew install python
- brew install awscli

script:
- ../bx/tools/bin/darwin/genie --with-shared-lib --with-tools --gcc=osx gmake
- make -C .build/projects/gmake-osx config=release64 CFLAGS="-mmacosx-version-min=10.9 -D BGFX_CONFIG_RENDERER_METAL=1 -D BGFX_CONFIG_RENDERER_OPENGL=1" LDFLAGS=-mmacosx-version-min=10.9 bgfx-shared-lib
- make -C .build/projects/gmake-osx config=release64 CFLAGS=-mmacosx-version-min=10.9 LDFLAGS=-mmacosx-version-min=10.9 geometryc
- make -C .build/projects/gmake-osx config=release64 CFLAGS=-mmacosx-version-min=10.9 LDFLAGS=-mmacosx-version-min=10.9 texturec
- make -C .build/projects/gmake-osx config=release64 CFLAGS=-mmacosx-version-min=10.9 LDFLAGS=-mmacosx-version-min=10.9 texturev
- make -C .build/projects/gmake-osx config=release64 CFLAGS=-mmacosx-version-min=10.9 LDFLAGS=-mmacosx-version-min=10.9 shaderc
- strip -u -r .build/osx64_clang/bin/libbgfx-shared-libRelease.dylib
- "aws s3 cp .build/osx64_clang/bin/libbgfx-shared-libRelease.dylib s3://build.lwjgl.org/nightly/macosx/x64/libbgfx.dylib --acl public-read --storage-class REDUCED_REDUNDANCY --cache-control \"public, must-revalidate, proxy-revalidate, max-age=0\""
- "git log --first-parent --pretty=format:%H HEAD~2..HEAD~1 > libbgfx.dylib.git"
- "aws s3 cp libbgfx.dylib.git s3://build.lwjgl.org/nightly/macosx/x64/ --acl public-read --storage-class REDUCED_REDUNDANCY --cache-control \"public, must-revalidate, proxy-revalidate, max-age=0\""
- "aws s3 cp .build/osx64_clang/bin/geometrycRelease s3://build.lwjgl.org/nightly/macosx/x64/bgfx-tools/geometryc --acl public-read --storage-class REDUCED_REDUNDANCY --cache-control \"public, must-revalidate, proxy-revalidate, max-age=0\""
- "aws s3 cp .build/osx64_clang/bin/texturecRelease s3://build.lwjgl.org/nightly/macosx/x64/bgfx-tools/texturec --acl public-read --storage-class REDUCED_REDUNDANCY --cache-control \"public, must-revalidate, proxy-revalidate, max-age=0\""
- "aws s3 cp .build/osx64_clang/bin/texturevRelease s3://build.lwjgl.org/nightly/macosx/x64/bgfx-tools/texturev --acl public-read --storage-class REDUCED_REDUNDANCY --cache-control \"public, must-revalidate, proxy-revalidate, max-age=0\""
- "aws s3 cp .build/osx64_clang/bin/shadercRelease s3://build.lwjgl.org/nightly/macosx/x64/bgfx-tools/shaderc --acl public-read --storage-class REDUCED_REDUNDANCY --cache-control \"public, must-revalidate, proxy-revalidate, max-age=0\""
